// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['desktop']['App']['Close']();
}

export function GetSettings() {
  return window['go']['desktop']['App']['GetSettings']();
}

export function RecentSamples(arg1) {
  return window['go']['desktop']['App']['RecentSamples'](arg1);
}

export function RecentSnapshots(arg1) {
  return window['go']['desktop']['App']['RecentSnapshots'](arg1);
}

export function Series(arg1, arg2) {
  return window['go']['desktop']['App']['Series'](arg1, arg2);
}

export function SeriesRange(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['SeriesRange'](arg1, arg2, arg3);
}

export function SetSettings(arg1) {
  return window['go']['desktop']['App']['SetSettings'](arg1);
}

export function Startup(arg1) {
  return window['go']['desktop']['App']['Startup'](arg1);
}
