// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {storage} from '../models';
import {context} from '../models';

export function Close():Promise<void>;

export function GetSettings():Promise<config.Settings>;

export function RecentSamples(arg1:number):Promise<Array<storage.Sample>>;

export function RecentSnapshots(arg1:number):Promise<Array<storage.Sample>>;

export function Series(arg1:string,arg2:number):Promise<Array<storage.SeriesPoint>>;

export function SetSettings(arg1:config.Settings):Promise<config.Settings>;

export function Startup(arg1:context.Context):Promise<void>;
